[project]
name = "facecog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepface>=0.0.93",
    "numpy>=2.1.3",
    "opencv-python-headless>=4.11.0.86",
    "tqdm>=4.67.1",
]
